# Generated by Django 5.2.1 on 2025-06-04 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedfile_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
