# Generated by Django 5.2.1 on 2025-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedfile_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
