# Generated by Django 5.2.1 on 2025-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_uploadedfile_id_uploadedfile_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
