# Generated by Django 5.2.1 on 2025-06-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uploadedfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='status',
        ),
    ]
