# Generated by Django 5.2.1 on 2025-06-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_flashcardset_flashcard_set_quizset_quizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='set',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='set',
        ),
        migrations.RemoveField(
            model_name='quizset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='quizset',
            name='user',
        ),
        migrations.DeleteModel(
            name='FlashcardSet',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizSet',
        ),
    ]
